server:
  error:
    include-stacktrace: on_param

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

jpa:
  hibernate:
    ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG